name: seqprep
owner: galaxyworks
description: SeqPrep is a program to merge paired end Illumina reads that are overlapping into a single longer read.
homepage_url: https://github.com/jstjohn/SeqPrep
remote_repository_url: https://github.com/galaxyproject/tools-iuc/tree/master/tools/iqtree/
categories:
  - Sequence Analysis
